// <auto-generated />
using DoubleDriver.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoubleDriver.Migrations
{
    [DbContext(typeof(DoubleDriverContext))]
    partial class DoubleDriverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoubleDriver.Models.BunqUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("server_public_key");

                    b.Property<string>("token");

                    b.Property<int>("user_id");

                    b.Property<string>("user_private_key");

                    b.Property<string>("user_public_key");

                    b.HasKey("Id");

                    b.ToTable("BunqUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
